markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 晓风Well
host: wwsun.github.com
desc: 这里写的不是博客，而是分享的情怀

custom:
    category:
        default: Blog
        another: Another 
    categories:
      - name:  default
        title: Blog

      - name:  another
        title: Another 
meta:
    author:
        name: Weiwei SUN
        email: ww.sun@outlook.com
        disqus: wwsun                              # Disqus缩略标识
        gcse: 017273734144320215856:r-n1xry8woo     # Google自定义搜索标识ID
        github: wwsun                               # GitHub账号
        gravatar: 48b4b2d677d28780288ab93737230019  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
